import Head from "next/head";

//Components

export default function about() {
	return (
		<>
			<Head>
				<title>About</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1> Pagina About </h1>
			</main>
		</>
	);
}
