import Head from "next/head";
import styles from "../styles/dashboard.module.scss";

//Components
import Dashboard from "../Components/Dashboard";

export default function dashboard() {
	return (
		<>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.dashboard}`}>
				<Dashboard />
			</main>
		</>
	);
}
